[package]
name = "poston"
version = "0.2.1"
authors = ["Takeru Sato <type.in.type@gmail.com>"]
description = "Yet another Fluentd logger for Rust"
documentation = "https://github.com/tkrs/poston"
homepage = "https://github.com/tkrs/poston"
repository = "https://github.com/tkrs/poston.git"
readme = "README.md"
license = "MIT"
keywords = ["fluentd", "fluentd-logger"]
categories = ["network-programming"]

[badges]
circle-ci = { repository = "tkrs/poston" }
maintenance = { status = "experimental" }

[dependencies]
backoff = "0.1.2"
base64 = "0.9.2"
log = "0.4.3"
rmp = "0.8.7"
rmp-serde = "0.13.7"
serde = "1.0.70"
serde_derive = "1.0.70"
uuid = { version = "0.6.5", features = ["v4"] }

[dev-dependencies]
pretty_env_logger = "0.2.4"
lazy_static = "1.0.1"
rand = "0.5.4"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
panic = 'unwind'
incremental = true
overflow-checks = true
