version: 2
jobs:
  build:
    docker:
      - image: rust:slim
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-cargo-{{ checksum "Cargo.toml" }}
            - deps-cargo-
      - run: cargo build --verbose --all
      - run: cargo test --verbose --all
      - save_cache:
          key: deps-cargo-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
