steps_template: &steps_template
  steps:
    - checkout
    - run: apt-get update && apt-get -y install libssl-dev pkg-config cmake zlib1g-dev
    - run: rustup show
    - restore_cache:
        keys:
          - cargo-tarpaulin-{{ .Environment.CIRCLE_JOB }}-v0.6.5
    - restore_cache:
        keys:
          - deps-cargo-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
          - deps-cargo-{{ .Environment.CIRCLE_JOB }}-
          - deps-cargo--{{ checksum "Cargo.toml" }}
          - deps-cargo--
    - run: cargo +nightly fmt -- --color=always --check
    - run: cargo +nightly clippy
    - run: cargo build --verbose --all
    - run: cargo test --verbose --all
    - run: |
        if [ "${CIRCLE_JOB}" != "version" ]; then exit 0; fi
        if ! cargo tarpaulin --help > /dev/null 2>&1; then
          RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin
        fi
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
    - save_cache:
        key: cargo-tarpaulin-{{ .Environment.CIRCLE_JOB }}-v0.6.5
        paths:
          - /usr/local/cargo/bin/cargo-tarpaulin
    - save_cache:
        key: deps-cargo-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
        paths:
          - ~/.cargo
version: 2
jobs:
  version:
    docker:
      - image: quay.io/tkrs/docker-rust:1.28.0
    <<: *steps_template
  stable:
    docker:
      - image: quay.io/tkrs/docker-rust:stable
        environment:
          RUSTUP_TOOLCHAIN: stable
    <<: *steps_template
  beta:
    docker:
      - image: quay.io/tkrs/docker-rust:beta
        environment:
          RUSTUP_TOOLCHAIN: beta
    <<: *steps_template
  nightly:
    docker:
      - image: quay.io/tkrs/docker-rust:nightly
        environment:
          RUSTUP_TOOLCHAIN: nightly
    <<: *steps_template
workflows:
  version: 2
  build:
    jobs:
      - version
      - stable
      - beta
      - nightly
  stable_schedule:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - stable
  beta_schedule:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - beta
  nightly_schedule:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - nightly
