steps_template: &steps_template
  steps:
    - checkout
    - restore_cache:
        keys:
          - deps-cargo-{{ checksum "Cargo.toml" }}
          - deps-cargo-
    - run: cargo +nightly fmt -- --color=always --error-on-unformatted --write-mode=check
    - run: cargo +nightly clippy
    - run: cargo build --verbose --all
    - run: cargo test --verbose --all
    - save_cache:
        key: deps-cargo-{{ checksum "Cargo.toml" }}
        paths:
          - ~/.cargo
version: 2
jobs:
  stable:
    docker:
      - image: quay.io/tkrs/docker-rust:stable
    <<: *steps_template
  beta:
    docker:
      - image: quay.io/tkrs/docker-rust:beta
    <<: *steps_template
  nightly:
    docker:
      - image: quay.io/tkrs/docker-rust:nightly
    <<: *steps_template
workflows:
  version: 2
  build:
    jobs:
      - stable
      - beta
      - nightly
