steps_template: &steps_template
  steps:
    - checkout
    - run: apt-get update && apt-get -y install libssl-dev pkg-config cmake zlib1g-dev
    - restore_cache:
        keys:
          - deps-cargo-{{ checksum "Cargo.toml" }}
          - deps-cargo-
    - run: cargo +nightly fmt -- --color=always --error-on-unformatted --check
    - run: cargo +nightly clippy
    - run: cargo build --verbose --all
    - run: cargo test --verbose --all
    - run: |
        if [ "${CIRCLE_JOB}" != "version" ]; then exit 0; fi
        if ! cargo tarpaulin --help > /dev/null 2>&1; then
          RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
        fi
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
    - save_cache:
        key: deps-cargo-{{ checksum "Cargo.toml" }}
        paths:
          - ~/.cargo
version: 2
jobs:
  version:
    docker:
      - image: quay.io/tkrs/docker-rust:1.27.0
    <<: *steps_template
  stable:
    docker:
      - image: quay.io/tkrs/docker-rust:stable
    <<: *steps_template
  beta:
    docker:
      - image: quay.io/tkrs/docker-rust:beta
    <<: *steps_template
  nightly:
    docker:
      - image: quay.io/tkrs/docker-rust:nightly
    <<: *steps_template
workflows:
  version: 2
  build:
    jobs:
      - version
      - stable
      - beta
      - nightly
