version: 2.1

commands:
  build:
    steps:
      - checkout
      - run: rustup show
      - run: rustup component add rustfmt clippy
      - restore_cache:
          keys:
            - deps-v1-cargo-{{ checksum "Cargo.toml" }}-{{ .Environment.CIRCLE_JOB }}
            - deps-v1-cargo-{{ checksum "Cargo.toml" }}
      - run: cargo fmt -- --color=always --check
      - run: cargo clippy --workspace -- -D warnings
      - run: cargo test --verbose --workspace
      - run: cargo build --verbose --workspace
      - save_cache:
          key: deps-v1-cargo-{{ checksum "Cargo.toml" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - /usr/loca/cargo

jobs:
  stable:
    docker:
      - image: circleci/rust
        environment:
          RUSTUP_TOOLCHAIN: stable
    steps:
      - build
  beta:
    docker:
      - image: circleci/rust
        environment:
          RUSTUP_TOOLCHAIN: beta
    steps:
      - build
  nightly:
    docker:
      - image: circleci/rust
        environment:
          RUSTUP_TOOLCHAIN: nightly
    steps:
      - build

workflows:
  version: 2
  stable-build:
    jobs:
      - stable
  beta-build:
    jobs:
      - beta

  nightly-build:
    jobs:
      - nightly
