steps_template: &steps_template
  steps:
    - checkout
    - run: rustup show
    - restore_cache:
        keys:
          - deps-cargo-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
          - deps-cargo-{{ .Environment.CIRCLE_JOB }}-
          - deps-cargo--{{ checksum "Cargo.toml" }}
          - deps-cargo--
    - run: cargo fmt -- --color=always --check
    - run: cargo clippy --all -- -D warnings
    - run: cargo clean
    - run: RUSTFLAGS="-C link-dead-code" cargo test --verbose --all --no-run
    - run: |
        if [ "${CIRCLE_JOB}" != "version" ]; then
          cargo test --verbose --all
        else
          cargo kcov --verbose --no-clean-rebuild --no-fail-fast --all
          bash <(curl -s https://codecov.io/bash) -s ./target/cov
        fi
    - save_cache:
        key: deps-cargo-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
        paths:
          - ~/.cargo
version: 2
jobs:
  version:
    docker:
      - image: quay.io/tkrs/docker-rust:1.32.0
    <<: *steps_template
  stable:
    docker:
      - image: quay.io/tkrs/docker-rust:stable
        environment:
          RUSTUP_TOOLCHAIN: stable
    <<: *steps_template
  beta:
    docker:
      - image: quay.io/tkrs/docker-rust:beta
        environment:
          RUSTUP_TOOLCHAIN: beta
    <<: *steps_template
  nightly:
    docker:
      - image: quay.io/tkrs/docker-rust:nightly
        environment:
          RUSTUP_TOOLCHAIN: nightly
    <<: *steps_template
workflows:
  version: 2
  build:
    jobs:
      - version
      - stable
      - beta
      - nightly
  stable_schedule:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - stable
  beta_schedule:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - beta
  nightly_schedule:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - nightly
