name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.61.0
          - stable
          - nightly
    name: Test and Build - ${{ matrix.version }}
    runs-on: ubuntu-latest
    services:
      fluentd:
        image: fluentd
        ports:
          - 24224:24224
    steps:
      - uses: actions/checkout@v3
      - name: Install ${{ matrix.version }}
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          target: x86_64-unknown-linux-gnu
          components: rustfmt
      - name: Install sccache
        env:
          SCCACHE_LINK: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: v0.3.3
        run: |
          mkdir -p ~/.cache/sccache
          curl -L "$SCCACHE_LINK/$SCCACHE_VERSION/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz" | tar xz
          echo "$PWD/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl/" >> $GITHUB_PATH
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - run: cargo fmt -- --color=always --check
      - run: cargo check --tests --workspace --verbose
      - run: cargo test --workspace --no-fail-fast -- --nocapture
      - run: cargo build --workspace --verbose
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain and components
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          components: clippy
      - run: cargo clippy --workspace --verbose
