name: Create Rlease Tag

on:
  push:
    branches: [master]

jobs:
  create-tag:
    environment: crates-io
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.commits[0].message, 'chore(release):') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Setup git user
        run: |
          git config user.email "type.in.type@gmail.com"
          git config user.name "Takeru Sato"
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - run: sudo npm install -g standard-version
      - name: Create tag
        run: standard-version --skip.changelog --skip.commit
      - name: Publish tag
        run: git push --follow-tags
